services:
  twentytwentyone:
    image: twentytwentyone
    build:
      context: src/wp-content/themes/twentytwentyone
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
